#!/bin/bash
DATAX_HOME=/opt/soft/datax/job/2207A/zirao_lv/2207A/zirao_lv
# 如果传入日期则do_date等于传入的日期，否则等于前一天日期
if [ -n "$2" ] ;then
    do_date=$2
else
    do_date=`date -d "-1 day" +%F`
fi

#处理目标路径，此处的处理逻辑是，如果目标路径不存在，则创建；若存在，则清空，目的是保证同步任务可重复执行
handle_targetdir() {
  hadoop fs -test -e $1
  if [[ $? -eq 1 ]]; then
    echo "路径$1不存在，正在创建......"
    hadoop fs -mkdir -p $1
  else
    echo "路径$1已经存在"
    fs_count=$(hadoop fs -count $1)
    content_size=$(echo $fs_count | awk '{print $3}')
    if [[ $content_size -eq 0 ]]; then
      echo "路径$1为空"
    else
      echo "路径$1不为空，正在清空......"
      hadoop fs -rm -r -f $1/*
    fi
  fi
}

#数据同步
import_data() {
  datax_config=$1
  target_dir=$2
  handle_targetdir $target_dir
  python $DATAX_HOME/bin/datax.py -p" -Dtargetdir=$target_dir" $datax_config
}

case $1 in
"order_info")
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.order_info.json /2207A/lvzirao/origin_data/db/order_info/$do_date
  ;;
"order_detail")
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.order_detail.json /2207A/lvzirao/origin_data/db/order_detail/$do_date
  ;;
"sku_info")
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.sku_info.json /2207A/lvzirao/origin_data/db/sku_info/$do_date
  ;;
"user_info")
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.user_info.json /2207A/lvzirao/origin_data/db/user_info/$do_date
  ;;
"comment_info")
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.comment_info.json /2207A/lvzirao/origin_data/db/comment_info/$do_date
  ;;
"base_category1")
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.base_category1.json /2207A/lvzirao/origin_data/db/base_category1/$do_date
  ;;
"base_category2")
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.base_category2.json /2207A/lvzirao/origin_data/db/base_category2/$do_date
  ;;
"base_category3")
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.base_category3.json /2207A/lvzirao/origin_data/db/base_category3/$do_date
  ;;
"all")
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.order_info.json /2207A/lvzirao/origin_data/db/order_info/$do_date
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.order_detail.json /2207A/lvzirao/origin_data/db/order_detail/$do_date
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.sku_info.json /2207A/lvzirao/origin_data/db/sku_info/$do_date
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.user_info.json /2207A/lvzirao/origin_data/db/user_info/$do_date
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.comment_info.json /2207A/lvzirao/origin_data/db/comment_info/$do_date
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.base_category1.json /2207A/lvzirao/origin_data/db/base_category1/$do_date
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.base_category2.json /2207A/lvzirao/origin_data/db/base_category2/$do_date
  import_data /opt/soft/datax/job/2207A/zirao_lv/import/gmall.base_category3.json /2207A/lvzirao/origin_data/db/base_category3/$do_date
  ;;
esac